#ifndef _X86_ASM_PAGE_TYPES_H
#define _X86_ASM_PAGE_TYPES_H

#define PAGE_SHIFT 12
#define PAGE_SIZE (1UL << PAGE_SHIFT)
#define PAGE_MASK (~(PAGE_SIZE - 1))

#define PMD_PAGE_SIZE (1UL) << PMD_SHIFT)
#define PMD_PAGE_MASK (~(PMD_PAGE_SIZE - 1))

#define PUD_PAGE_SIZE (1UL << PUD_SHIFT)
#define PUD_PAGE_MASK (~(PUD_PAGE_SIZE - 1))

#define MAX_PHYSMEM_BITS 46
#define MAXMEM (1ULL << MAX_PHYSMEM_BITS)

#endif /* _X86_ASM_PAGE_TYPES_H */
