#ifndef _X86_ASM_PAGE_TYPES_H
#define _X86_ASM_PAGE_TYPES_H

#define PAGE_SHIFT 12
#define PAGE_SIZE (1ULL << PAGE_SHIFT)
#define PAGE_MASK (~(PAGE_SIZE - 1))

#define MAX_PHYSMEM_BITS 46
#define MAXMEM (1ULL << MAX_PHYSMEM_BITS)

#endif /* _X86_ASM_PAGE_TYPES_H */
